openapi: 3.0.3
info:
  title: nautible-app-ms-stock
  version: 1.0.0-SNAPSHOT
servers:
- url: http://localhost:8080/
paths:
  /stock/reserveAllocate/:
    post:
      tags:
        - RestStockService
      operationId: reserveAllocate
      summary: SAGA。在庫の引当予約。引当履歴を作成する。
      description: SAGA。在庫の引当予約を行う（数量を減らして、予約数量を増やす）。PENDINGステータスで引当履歴を作成する（Semantic Lock カウンターメジャー）。
      requestBody:
        content:
          "application/cloudevents+json":
            schema:
              type: string
              format: byte
      responses:
        200:
          description: successful operation
          content: {}
  /stock/approveAllocate/:
    post:
      tags:
        - RestStockService
      operationId: approveAllocate
      summary: SAGA。在庫の引当を承認する。引当履歴を更新する。
      description: SAGA。引当予約を承認する。引当処理を実施し、引当履歴のステータスを引当済みに変更する（Semantic Lock カウンターメジャー）。
      requestBody:
        content:
          "application/cloudevents+json":
            schema:
              type: string
              format: byte
      responses:
        200:
          description: successful operation
          content: {}
  /stock/rejectAllocate/:
    post:
      tags:
        - RestStockService
      operationId: rejectAllocate
      summary: SAGA。在庫予約の却下。引当履歴を更新する。
      description: SAGA。引当予約を却下する。引当予約を取り消す（数量を増やして、予約数量を減らす）。引当履歴のステータスを却下に変更する（Semantic Lock カウンターメジャー）
      requestBody:
        content:
          "application/cloudevents+json":
            schema:
              type: string
              format: byte
      responses:
        200:
          description: successful operation
          content: {}
components:
  schemas:
    StockReserveAllocateRequest:
      type: object
      required:
        - requestId
        - productId
        - quantity
      properties:
        requestId:
          description: 処理要求を一意に表すリクエストId。
          type: string
          example: O0000000001-1234567890
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductAllocateDetail'
    ProductAllocateDetail:
      type: object
      required:
        - productId
        - quantity
      properties:
        productId:
          type: integer
          description: 商品Id
          format: int32
          example: 123
        quantity:
          type: integer
          description: 数量
          format: int32
          example: 123
    StockApproveAllocateRequest:
      type: object
      required:
        - requestId
      properties:
        requestId:
          description: 引当予約の承認対象のリクエストId
          type: string
          example: O0000000001-1234567890
    StockRejectAllocateRequest:
      type: object
      required:
        - requestId
      properties:
        requestId:
          description: 引当予約の却下対象のリクエストId
          type: string
          example: O0000000001-1234567890

